### ISSUE TITLE
Void

### ISSUE THREAD

**Issue by Greywan** [huajiejin/yolov8-swiftui#1]
Thank you for your work, but why do i run without any result？
![IMG_0122](https://github.com/huajiejin/yolov8-swiftui/assets/61035902/d80ac38d-ef6a-4ca5-ada8-c1d5958e9dbb)

**Comment by huajiejin** [comment]
Thank you for bringing this to my attention. I'm sorry for any inconvenience. This project was an experimental test and hasn't been completed yet. I'll investigate the issue and update the code to address the problem. I'll let you know of any progress.

**Comment by huajiejin** [comment]
I've made some updates to the code that should fix the problem you encountered.

See https://github.com/huajiejin/yolov8-swiftui/commit/2e6ac791782287be6575a14a584449c587edbe60

**Comment by Greywan** [comment]
Thanks for your reply and efforts, are there any plans to launch an ios app project for yolov8-seg? Or modifications to the existing project?

**Comment by huajiejin** [comment]
Thank you for your feedback, Greywan. At the moment, there are no specific plans to launch an iOS app project for yolov8-seg or make modifications to the existing project. However, your suggestion is noted and will be considered for future development. Feel free to open a new issue if you have any other ideas or requests. I'm marking this issue as closed for now.

**Comment by Greywan** [comment]
> Thank you for your feedback, Greywan. At the moment, there are no specific plans to launch an iOS app project for yolov8-seg or make modifications to the existing project. However, your suggestion is noted and will be considered for future development. Feel free to open a new issue if you have any other ideas or requests. I'm marking this issue as closed for now.

Thank you for your reply~
